{% set name = "pytask-environment" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask_environment-{{ version }}.tar.gz
  sha256: 2bce297a9d070301450c75f959229e38078b6bbb5f880cbb284e34b229bacb70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - toml
  run:
    - click
    - pony
    - pytask >=0.1.7
    - python >=3.7

test:
  imports:
    - pytask_environment
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-environment
  summary: Detect changes in your pytask environment and abort a project build.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/pytask-dev/pytask-environment
  dev_url: https://github.com/pytask-dev/pytask-environment

extra:
  recipe-maintainers:
    - tobiasraabe
