{% set name = "pytask-environment" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytask-environment-{{ version }}.tar.gz
  sha256: 8bf15c73404b033b1625590170c4e29176ea0dd53e8735b2f22e5ba85a17ad24

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - pony
    - pytask >=0.0.7
    - python >=3.6

test:
  imports:
    - pytask_environment
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytask-dev/pytask-environment
  summary: Detect changes in your pytask environment and abort a project build.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/pytask-dev/pytask-environment
  dev_url: https://github.com/pytask-dev/pytask-environment

extra:
  recipe-maintainers:
    - tobiasraabe
